require: rubocop-rails
inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - 'spec/dummy/db/schema.rb'
    - 'app/strategies/fin_calendar_*'
    - 'app/strategies/name_normalizer.rb'

# The behavior of RuboCop can be controlled via the .rubocop.yml
# configuration file. It makes it possible to enable/disable
# certain cops (checks) and to alter their behavior if they accept
# any parameters. The file can be placed either in your home
# directory or in some project directory.
#
# RuboCop will start looking for the configuration file in the directory
# where the inspected file is and continue its way up to the root directory.
#
# See https://github.com/rubocop-hq/rubocop/blob/master/manual/configuration.md

Layout/AlignParameters:
  EnforcedStyle: with_fixed_indentation

# Offense count: 10
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyleAlignWith, AutoCorrect, Severity.
# SupportedStylesAlignWith: keyword, variable, start_of_line
Layout/EndAlignment:
  EnforcedStyleAlignWith: variable

# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle.
# SupportedStyles: empty_lines, empty_lines_except_namespace, empty_lines_special, no_empty_lines, beginning_only, ending_only
Layout/EmptyLinesAroundClassBody:
  EnforcedStyle: empty_lines
  Exclude:
    - 'Guardfile'
    - 'db/**/*'
    - 'config/**/*'
    - 'spec/**/*'
    - 'test/**/*'

Layout/SpaceAroundOperators:
    Enabled: false

# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle.
# SupportedStyles: space, no_space
Layout/SpaceInsideParens:
  Enabled: false

Layout/SpaceInsideStringInterpolation:
  Enabled: false

# Configuration parameters: CountComments.
Metrics/ModuleLength:
  Max: 120
  Exclude:
    - 'lib/common/format.rb'

Naming/VariableNumber:
  Enabled: false

Style/AsciiComments:
  Enabled: false

# Offense count: 1
# Cop supports --auto-correct.
# Configuration parameters: AutoCorrect, EnforcedStyle.
# SupportedStyles: nested, compact
Style/ClassAndModuleChildren:
  Exclude:
    - 'test/test_helper.rb'

Style/Documentation:
  Exclude:
    - 'spec/**/*'
    - 'test/**/*'
    - 'app/helpers/application_helper.rb'
    - 'app/mailers/application_mailer.rb'
    - 'app/models/application_record.rb'
    - 'config/application.rb'

Style/DoubleNegation:
  Exclude:
    - 'app/strategies/fin_calendar_meeting_builder.rb'
    - 'app/strategies/user_training_story_accessibility.rb'
    - 'app/strategies/user_training_accessibility.rb'
    - 'app/strategies/training_accessibility.rb'
    - 'app/strategies/swimmer_user_strategy.rb'

# Cop supports --auto-correct.
Style/ExpandPathArguments:
  Exclude:
    - 'bin/rails'
    - 'bin/rake'
    - 'spec/rails_helper.rb'

Style/FormatStringToken:
  Enabled: false

Style/FrozenStringLiteralComment:
  Exclude:
    - 'app/strategies/begin_time_calculator.rb'
    - 'app/strategies/geocoding_parser.rb'
    - 'spec/strategies/begin_time_calculator_spec.rb'

Style/MixinUsage:
  Exclude:
    - 'bin/*'

# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle.
# SupportedStyles: literals, strict
Style/MutableConstant:
  EnforcedStyle: strict

# Cop supports --auto-correct.
Style/RedundantBegin:
  Exclude:
    - 'bin/yarn'

Style/Semicolon:
  Exclude:
    - 'spec/strategies/fin_calendar_swimming_pool_builder_spec.rb'

# Cop supports --auto-correct.
Style/StderrPuts:
  Exclude:
    - 'bin/yarn'

# Cop supports --auto-correct.
# Configuration parameters: MinSize.
# SupportedStyles: percent, brackets
Style/SymbolArray:
  EnforcedStyle: brackets

# Configuration parameters: EnforcedStyle.
# SupportedStyles: slashes, arguments
Rails/FilePath:
  Exclude:
    - 'lib/tasks/cucumber.rake'
